import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp,writeFile,rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { Catalog } from '../backend/catalog.js';
test('catalog filters accents, IDs and modules; paginates and invalidates on save change',async t=>{
 const directory=await mkdtemp(join(tmpdir(),'motuca-catalog-'));
 t.after(()=>rm(directory,{recursive:true,force:true}));
 let session='save1',connected=true;
 const items=Array.from({length:110},(_,i)=>({id:`Mod.Item${i}`,name:`Água ${String(i).padStart(3,'0')}`,module:'Mod'}));
 const bridge={directory,status:async()=>({connected,state:{session}}),read:async()=>({session:'save1',count:110})};
 await writeFile(join(directory,'catalog.txt'),items.map(item=>JSON.stringify(item)).join('\n'));
 const catalog=new Catalog(bridge);
 const query=q=>catalog.query(new URLSearchParams(q));
 const first=await query('q=agua');assert.equal(first.total,110);assert.equal(first.items.length,48);assert.equal(first.pages,3);
 assert.equal((await query('page=3')).items.length,14);
 assert.equal((await query('q=Mod.Item109')).items[0].id,'Mod.Item109');
 assert.equal((await query('module=Base')).total,0);
 session='save2';await assert.rejects(query(''),e=>e.status===503);
 connected=false;await assert.rejects(query(''),e=>e.status===503);
});
